version: "3.7"

x-enviroment: &common-variables
    MONGO_INITDB_DATABASE: "go-api-db"
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "rootpassword"

services:
    database:
        image: mongo:latest
        container_name: "mongodb"
        environment: *common-variables
        volumes:
            - mongodb_data_container:/data/db
    app:
        build: .
        container_name: "app"
        environment:
            <<: *common-variables
            MONGO_SERVER: "mongodb"
            MONGO_INITDB_DATABASE_COLL: "users"
            SERVER_PORT: 9090
        restart: "always"
        depends_on:
            - database
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - app
        ports: 
            - "80:80"

volumes:
  mongodb_data_container: