version: "3.7"

x-enviroment: &common-variables
    MONGO_INITDB_DATABASE: "go-api-db"
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "rootpassword"


services:
    database:
        image: mongo:latest
        container_name: "mongodb"
        environment: *common-variables
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
    app:
        build: .
        container_name: "api"
        environment:
            <<: *common-variables
            MONGO_SERVER: "mongodb"
            MONGO_INITDB_DATABASE_COLL: "users"
        ports:
            - 9090:9090
        depends_on:
            - database

volumes:
  mongodb_data_container: